language: java
sudo: false
install: true
addons:
  sonarcloud:
    organization: "spoorthyv-github"
    token:
      secure: "ad566dd5a3a33a8bf7ea2b3f9b17815c0f58af54"
jdk:
  - oraclejdk8
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'